name: Test, Build and Deploy
on:
  push: 
    branches: 
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Use Node.js 13
      uses: actions/setup-node@v1
      with:
        node-version: 13

    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - uses: actions/cache@v1
      id: elm-cache
      with:
        path: ~/.elm
        key: ${{ runner.os }}-elm--home-${{ hashFiles('**/elm.json') }}

    - name: Test
      run: |
        npm install elm-test
        node node_modules/elm-test/bin/elm-test

    - name: Build demo
      run: |
        cd demo
        npm install
        npm run build
        cd ..

    - name: Deploy demo
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: demo/build
        CLEAN: true

    - uses: dillonkearns/elm-publish-action@master
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        path-to-elm: ./demo/node_modules/elm/bin/elm
